name: Keep Supabase Alive

on:
  schedule:
     - cron: '0 0 */2 * *'  # every 3 days at midnight
  workflow_dispatch: # allows manual run from GitHub Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase REST API
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://hsupmflvueacqfmmallb.supabase.co/rest/v1/ | grep 200 || echo "Ping failed"
